[dependencies]
cl-traits = { features = ["alloc"], path = "../cl-traits" }

[[example]]
name = "manual"
path = "manual.rs"

[package]
edition = "2018"
license = "Apache-2.0"
name = "cl-traits-examples"
publish = false
version = "0.0.0"
